### ISSUE TITLE
Cookies not getting passed for CORS request

### ISSUE THREAD

**Issue by prakkarp** [thenativeweb/http-browserify-2#10]
For CORS requests, the cookies are not getting passed. This is due to the fact that xhr.withCredentials is set to false in request.js. Instead of hard-coding it to false, can this be a configurable value passed using the options?

**Comment by goloroden** [comment]
IMHO we could make this configurable.

Would you mind sending a PR (including updated tests and documentation)?

**Comment by goloroden** [comment]
Closed due to missing activity.
