### ISSUE TITLE
TypeError: Cannot read property 'PassThrough' of undefined

### ISSUE THREAD

**Issue by chtimi59** [thenativeweb/http-browserify-2#11]
# Context: (bundling an umd  lib for Webpack 4)

After running it in browser, I get this:
```
TypeError: Cannot read property 'PassThrough' of undefined 
```
```js
var stream = require('stream'),
    url = require('url');

var parseResponseHeaders = require('./parseResponseHeaders');

var PassThrough = stream.PassThrough;
```

And I actually I don't have stream on my "node_modules"  (not sure why webpack don't complains on it) anyway I guess a peerDependency is missing in your package.json

And I guess it should be the same for url (in my case, already bring it in my node_module)

**Comment by goloroden** [comment]
Won't fix, as this module is basically deprecated and we don't put any active effort into maintaining this any more.
