### ISSUE TITLE
Badges! (once the build is fixed)

### ISSUE THREAD

**Issue by jamestalmage** [thenativeweb/http-browserify-2#5]
Once the lint errors are handled, you really should add some badges showing you've got a passing build and good test coverage. Hopefully this will provide people with some confidence. I'm going to hop back on the substack/http-browserify issues list and tell people to start using this instead since development is slowed down over there. I'd like a passing automated build before I do that though.

When I run `grunt shell`, the browser opens and the tests do run, but that process never exits. I'm assuming things are different when running via sauce_labs?

**Comment by goloroden** [comment]
First of all: Thank you so much for your work and your great help :-)

We have now merged all your pull requests, and just released the new version `0.4.0` to npm which includes all of your changes and additions.

Regarding the badges, AFAWCS the Sauce Labs badges require that your build runs using TravisCI. Currently, we use CircleCI for all of our projects, and so far we had decided not to use a second build system "only" for getting badges. Maybe we are wrong on the missing CircleCI support, maybe you know more on this?

Regarding telling people to hop over: Thanks for your support, we greatly appreciate that :-)

We understand that you first would like to see an automated build. Basically, this is something that we would like to see as well… you know, the problem (as always ;-)) is having the time to set things up. Could you imagine helping us to get things running for this?

Regarding you last question: Yes, the process actually never exits. Unfortunately, this is a constraint that we have no influence on right now.

**Comment by jamestalmage** [comment]
Yeah,
I'm not sure on CircleCI, I use Travis for all my stuff. I did see [this](https://circleci.com/docs/status-badges), but that's CircleCI, not Sauce Labs.

Does the process exit on your sauce lab builds? Or do you not run the tests on CircleCi either?

**Comment by goloroden** [comment]
Right now we don't run them on CircleCI, only manually before committing and pushing.

**Comment by goloroden** [comment]
Won't fix.
