### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by NodeGuy** [thenativeweb/http-browserify-2#7]
I'm missing something.  How are we to use this given that Browserify isn't honoring the `browser` field in `package.json` (https://github.com/substack/node-browserify/issues/1250)?  Do you have a workaround?

**Comment by goloroden** [comment]
Thanks a lot for pointing this issue out!

Unfortunately, I don't know of a workaround, so I guess until someone else comes up with one, we'll have to wait until that bug in Browserify gets fixed.

Sorry :-(

**Comment by goloroden** [comment]
PS: What you can do, of course, is to directly `require` this module instead of requiring `http` and let Browserify do the replacement. Unfortunately, this will only work for a few scenarios… but anyway, perhaps better than nothing.

**Comment by NodeGuy** [comment]
Cool, thanks for letting me know.
