### ISSUE TITLE
Unsafe headers are not stripped

### ISSUE THREAD

**Issue by joepie91** [thenativeweb/http-browserify-2#8]
The original `http-browserify` [strips unsafe headers](https://github.com/substack/http-browserify/blob/17b2990010ebd39461d1117c1e2c50c25eab869f/lib/request.js#L157-L180), which prevents errors from occuring when these are set (when code assumes that it is running in a Node.js environment).

The result is this:

![selection_468](https://cloud.githubusercontent.com/assets/1663259/12323888/3d18d6a4-babf-11e5-82b4-7a0db253f0b4.png)

In order for `http-browserify-2` to truly be a drop-in replacement, this behaviour should probably be replicated.

**Comment by goloroden** [comment]
This is a good hint, thanks a lot :-)

Would you mind creating a PR?

**Comment by joepie91** [comment]
I might have a go at it in a bit. Right now, I'm still trying to get the module to work at all :) I use Webpack rather than Browserify, so that might take a while.

**Comment by goloroden** [comment]
Closed due to missing activity.
