### ISSUE TITLE
Unable to run tests due to erroneous require

### ISSUE THREAD

**Issue by joepie91** [thenativeweb/http-browserify-2#9]
When attempting to run tests (or analyse), the following occurs:

```
sven@linux-etoq:~/projects/http-browserify-2> grunt test-browser
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-checkbranch/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-checkpending/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-depcheck/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-dev-update/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-eslint/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-gitnobehind/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-release/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-shell/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-contrib-watch/tasks" not found.
Warning: Task "shell:test-browser" not found. Use --force to continue.

Aborted due to warnings.
sven@linux-etoq:~/projects/http-browserify-2> grunt analyse
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-checkbranch/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-checkpending/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-depcheck/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-dev-update/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-eslint/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-gitnobehind/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-release/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-shell/tasks" not found.
>> Tasks directory "/home/sven/projects/http-browserify-2/node_modules/tourism/node_modules/grunt-contrib-watch/tasks" not found.
Warning: Task "eslint" not found. Use --force to continue.

Aborted due to warnings.
```

The required dependencies are installed, but not in the `node_modules` folder of `tourism` (which is where it's looking), as I am using NPM 3, which deduplicates and flattens by default. Somewhere in the Grunt stack, something seems to be (incorrectly) assuming the fully-nested structure of NPM 2.

This is a fairly critical issue - until I can run tests, I won't be able to submit PRs.

Aside from that: this project is using an old version of `tourism`, and uses `0.x` version numbers. It would probably be a good idea to move to [semantic versioning](https://gist.github.com/joepie91/9b9dbd8c9ac3b55a65b2#semantic-versioning).

EDIT: Seems the issue might not actually be a require() call, but some other kind of filesystem read that explicitly expects nested dependencies.

**Comment by goloroden** [comment]
Yes, we use tourism for building, and that currently only works with npm 2. Sorry for that :-/

**Comment by joepie91** [comment]
Can't this be patched by using `require.resolve` rather than assuming that everything is in `node_modules`? Something like `require.resolve("grunt-checkbranch/tasks")` should give you the correct path of the module.

Either way, I can't write any tests until this issue is resolved (as downgrading to NPM 2 in my environment is not really an option), and I'd imagine that PRs without tests are not going to be merged...

**Comment by goloroden** [comment]
The solution we strive for is switching from `tourism` to [`roboter`](https://www.npmjs.com/package/roboter), which shouldn't be too hard, but we are currently having issues publishing npm modules to the registry.

So we will need to fix this before. If you want to, we would be very happy if you could address the migration to roboter :-)

**Comment by goloroden** [comment]
Closed due to missing activity.
